name: Update Dependencies

on:
  workflow_dispatch: # 手動実行可能化
  schedule: # https://docs.github.com/ja/actions/reference/events-that-trigger-workflows#scheduled
  - cron: '0 20 * * sun,wed' # '分 時 日 月 曜日' (UTC)

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v1
      
      - name: Update Dependencies
        run: flutter pub upgrade --major-versions
        
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: scheduled/update-packages
          delete-branch: true
          commit-message: '[自動] パッケージ更新'
          title: '[自動] パッケージ更新'
          body: |
            ## 概要
            パッケージ更新のPull Requestです。
            定期スケジュールに基づいて作成されています。
            
            レビュアーは動作確認を行い、必要であればコードを修正した上で、マージしてください。
            
            ---
            
            [create-pull-request](https://github.com/peter-evans/create-pull-request)により作成されました。
          labels: scheduled
#           assignees: 
#           reviewers: 
