targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**/result.dart
            - lib/**/message.dart
            - lib/**/*_entity.dart
            - lib/**/*_state.dart
      json_serializable:
        generate_for:
          include:
            - lib/**/*_entity.dart
            - lib/**/*_state.dart
        options:
          any_map: true
          explicit_to_json: true
