name: flutter_playground
description: Flutter Playground
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.1
  hooks_riverpod: ^0.14.0
  http: ^0.13.1
  intl: ^0.17.0
  rive: ^0.7.12
  shared_preferences: ^2.0.5
  video_player: ^2.0.2

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  json_serializable: ^4.1.0
  pedantic_mono: ^1.11.0+2

flutter:
  uses-material-design: true

  assets:
    - assets/images/pakutaso/
    - assets/animations/
